# Generated by Django 5.2.16 on 2026-08-03 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='tailors.tailor')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-attendance_date', '-created_at'],
                'indexes': [models.Index(fields=['attendance_date'], name='attendance__attenda_9d89bd_idx'), models.Index(fields=['tailor', 'attendance_date'], name='attendance__tailor__3bd7f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('tailor', 'attendance_date'), name='unique_attendance_per_tailor_date')],
            },
        ),
    ]
