# Generated by Django 5.2.16 on 2026-08-02 16:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Human-friendly unique order number, e.g. ORD-2026-0001.', max_length=20, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the order was received / cloth accepted.')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Optional expected delivery date.', null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CUTTING', 'Cutting'), ('STITCHING', 'Stitching'), ('READY', 'Ready'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=12)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line item amounts. Never floating-point.', max_digits=10)),
                ('collected_at', models.DateTimeField(blank=True, help_text='Set when the order becomes COLLECTED.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('PANT', 'Pant')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('measurement_version', models.PositiveIntegerField(blank=True, help_text='Measurement version used when ordering.', null=True)),
                ('measurement_snapshot', models.JSONField(blank=True, help_text='Immutable copy of the measurement values used for this item.', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-piece price in INR.', max_digits=10)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement', models.ForeignKey(blank=True, help_text='Reference to the exact measurement version used at order time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='customers.measurement')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CUTTING', 'Cutting'), ('STITCHING', 'Stitching'), ('READY', 'Ready'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], help_text='None for the initial NEW entry.', max_length=12, null=True)),
                ('to_status', models.CharField(choices=[('NEW', 'New'), ('CUTTING', 'Cutting'), ('STITCHING', 'Stitching'), ('READY', 'Ready'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, help_text='STAFF user who performed the transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_orde_order_d_d71205_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'order_date'], name='orders_orde_custome_d1ff33_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'garment_type'], name='orders_orde_order_i_7d7bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'changed_at'], name='orders_orde_order_i_7978aa_idx'),
        ),
    ]
