# Generated by Django 5.2.16 on 2026-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_measurement_armfold_loose_measurement_body_loose_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shirt_type',
            field=models.CharField(blank=True, choices=[('FULL', 'Full Shirt'), ('HALF', 'Half Shirt')], help_text='Shirt cut variant. Required for SHIRT items, always NULL for PANT. NULL is tolerated at the database level so pre-existing shirt lines are never silently reclassified.', max_length=4, null=True),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('garment_type', 'PANT'), ('shirt_type__isnull', True)), ('garment_type', 'SHIRT'), _connector='OR'), name='orderitem_shirt_type_only_on_shirt'),
        ),
    ]
