# Generated by Django 6.0.4 on 2026-08-03 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Saamu Tailors', max_length=100)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('established_year', models.PositiveIntegerField(default=1954)),
            ],
            options={
                'verbose_name': 'Shop Details',
                'verbose_name_plural': 'Shop Details',
            },
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('PARTIAL', 'Partial'), ('FINAL', 'Final'), ('REFUND', 'Refund')], default='PARTIAL', help_text='ADVANCE / PARTIAL / FINAL payment or a REFUND to the customer.', max_length=12),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='refunded_payment',
            field=models.ForeignKey(blank=True, help_text='For REFUND transactions, the original payment being reversed (audit trail). The original row is never modified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.customerpayment'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['payment_type'], name='billing_cus_payment_498ce8_idx'),
        ),
    ]
