# Generated by Django 6.0.4 on 2026-08-10 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_shopdetails_customerpayment_payment_type_and_more'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='customer_follow_up_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='Months of inactivity after which a customer receives a follow-up reminder. Used by the Reminders V1 customer follow-up rule.'),
        ),
        migrations.CreateModel(
            name='ManualReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short headline for the reminder.', max_length=200)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('reminder_date', models.DateField(help_text='Date this reminder is due / should be actioned.')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_manual_reminders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manual_reminders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Optional related customer for context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_reminders', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Optional related order for context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_reminders', to='orders.order')),
            ],
            options={
                'verbose_name': 'Manual Reminder',
                'verbose_name_plural': 'Manual Reminders',
                'ordering': ['-reminder_date', '-id'],
                'indexes': [models.Index(fields=['status', 'reminder_date'], name='billing_man_status_793ef6_idx'), models.Index(fields=['priority'], name='billing_man_priorit_01e76f_idx')],
            },
        ),
    ]
