# Generated by Django 5.2.16 on 2026-08-03 08:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('half_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('completed_pieces', models.PositiveIntegerField(default=0)),
                ('piece_rate_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('attendance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='tailors.tailor')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Entry',
                'verbose_name_plural': 'Payroll Entries',
                'ordering': ['tailor__full_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['period_start', 'period_end'], name='payroll_pay_period__8fe703_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status'], name='payroll_pay_status_c18070_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='payroll_period_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['payroll_period', 'tailor'], name='payroll_pay_payroll_544fa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('payroll_period', 'tailor'), name='unique_payroll_entry_per_period_tailor'),
        ),
    ]
