# Generated by Django 5.2.16 on 2026-08-03 11:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('tailors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='fixed_salary_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='salary_model',
            field=models.CharField(choices=[('PER_GARMENT', 'Per Garment'), ('FIXED_SALARY', 'Fixed Salary'), ('MIXED', 'Fixed + Per Garment')], default='PER_GARMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='TailorSalaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_model', models.CharField(choices=[('PER_GARMENT', 'Per Garment'), ('FIXED_SALARY', 'Fixed Salary'), ('MIXED', 'Fixed + Per Garment')], default='PER_GARMENT', max_length=20)),
                ('fixed_salary_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_configurations', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_configurations', to='tailors.tailor')),
            ],
            options={
                'verbose_name': 'Tailor Salary Configuration',
                'verbose_name_plural': 'Tailor Salary Configurations',
                'ordering': ['tailor__full_name', '-effective_from', '-id'],
                'indexes': [models.Index(fields=['tailor', 'effective_from'], name='payroll_tai_tailor__3695c3_idx'), models.Index(fields=['salary_model'], name='payroll_tai_salary__e7ae1a_idx'), models.Index(fields=['is_active'], name='payroll_tai_is_acti_b02fe8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fixed_salary_amount__gte', 0)), name='salary_config_fixed_amount_non_negative'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='salary_config_effective_dates_valid')],
            },
        ),
    ]
