# Generated by Django 5.2.16 on 2026-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], default='STAFF', help_text='Application role used for role-based access control.', max_length=10),
        ),
    ]
