# Generated by Django 5.2.16 on 2026-08-07 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the reset token (the raw token is never stored).', max_length=64)),
                ('used', models.BooleanField(default=False, help_text='True once the token has been consumed; single-use enforcement.')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The account the reset token was issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'indexes': [models.Index(fields=['user', 'used'], name='authenticat_user_id_ee9899_idx'), models.Index(fields=['token_hash'], name='authenticat_token_h_499884_idx')],
            },
        ),
    ]
