from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from apps.common.models import TimeStampedModel


class Role(models.TextChoices):
    """
    Application roles for Saamu Tailors.

    Exactly two roles exist:
    - OWNER: can log in and view permitted business information (view-only).
    - STAFF: the operational management user for business operations.

    These are application roles, independent of Django's ``is_staff`` flag.
    """

    OWNER = "OWNER", "Owner"
    STAFF = "STAFF", "Staff"


class User(AbstractUser):
    """
    Custom User Model for Saamu Tailors.

    Provides an explicit application ``role`` (OWNER/STAFF) used for
    role-based access control. Django's ``is_staff`` / ``is_superuser``
    flags are unrelated to the application role and never become a third role.
    """

    phone_number = models.CharField(max_length=20, blank=True, null=True)

    role = models.CharField(
        max_length=10,
        choices=Role.choices,
        default=Role.STAFF,
        help_text="Application role used for role-based access control.",
    )

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.username or self.email or f"User {self.id}"


class PasswordResetToken(TimeStampedModel):
    """Single-use password reset token record (Phase 22).

    The raw token is generated by Django's ``PasswordResetTokenGenerator`` and
    emailed to the user; only its SHA-256 digest is stored here, so a database
    leak never yields usable reset tokens. ``used`` enforces single-use; expiry
    (``PASSWORD_RESET_TIMEOUT``) and invalidation after a password change are
    enforced by the token generator itself, because the user's password hash is
    part of the token digest.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="password_reset_tokens",
        help_text="The account the reset token was issued for.",
    )
    token_hash = models.CharField(
        max_length=64,
        help_text="SHA-256 hex digest of the reset token (the raw token is never stored).",
    )
    used = models.BooleanField(
        default=False,
        help_text="True once the token has been consumed; single-use enforcement.",
    )
    used_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Password Reset Token"
        verbose_name_plural = "Password Reset Tokens"
        indexes = [
            models.Index(fields=["user", "used"]),
            models.Index(fields=["token_hash"]),
        ]

    def __str__(self):
        return f"Reset token for {self.user} ({'used' if self.used else 'active'})"
