# Generated by Django 5.2.16 on 2026-08-02 12:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=16)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=16)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('is_active', models.BooleanField(default=True, help_text='Archived customers are marked inactive but are retained so historical relationships remain intact.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['mobile_number'], name='customers_c_mobile__0be7f7_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('PANT', 'Pant')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('neck_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('chest_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('shoulder_width', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('sleeve_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('cuff_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('shirt_length', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('hip_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('thigh_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('knee_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('bottom_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('length', models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.customer')),
            ],
            options={
                'ordering': ['garment_type', 'version'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'garment_type', 'version'), name='uniq_customer_garment_version')],
            },
        ),
    ]
