# Generated by Django 5.2.16 on 2026-09-20 10:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='armfold_loose',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))]),
        ),
        migrations.AddField(
            model_name='measurement',
            name='body_loose',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))]),
        ),
        migrations.AddField(
            model_name='measurement',
            name='chest_loose',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))]),
        ),
        migrations.AddField(
            model_name='measurement',
            name='half_length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Measurement in inches.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300.0'))]),
        ),
    ]
