# Generated by Django 5.2.16 on 2026-08-03 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('tailors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('OTHER', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll.payrollentry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payroll_payments', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='tailors.tailor')),
            ],
            options={
                'verbose_name': 'Payroll Payment',
                'verbose_name_plural': 'Payroll Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['payroll_entry', 'payment_date'], name='payments_pa_payroll_eb3726_idx'), models.Index(fields=['tailor', 'payment_date'], name='payments_pa_tailor__52883e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_payment_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_date', models.DateField()),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('DEDUCTED', 'Deducted')], default='OUTSTANDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('deducted_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_deductions', to='payroll.payrollentry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_salary_advances', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='tailors.tailor')),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-advance_date', '-created_at'],
                'indexes': [models.Index(fields=['tailor', 'advance_date'], name='payments_sa_tailor__af47b3_idx'), models.Index(fields=['status'], name='payments_sa_status_4b02f6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_advance_amount_positive')],
            },
        ),
    ]
